// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dartfirebase_options
/// import '.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb6eS02GL8tGoTBOfvvfguOZsNyNNTNVo',
    appId: '1:22778761281:web:5e264c75160689af4a36c0',
    messagingSenderId: '22778761281',
    projectId: 'my-project-8e1a9',
    authDomain: 'my-project-8e1a9.firebaseapp.com',
    storageBucket: 'my-project-8e1a9.appspot.com',
    measurementId: 'G-2XZB56KH1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbbs3WIsz46kx4RaJrFnVhGVddhmpdPLk',
    appId: '1:22778761281:android:a854e731a315a8284a36c0',
    messagingSenderId: '22778761281',
    projectId: 'my-project-8e1a9',
    storageBucket: 'my-project-8e1a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqKZIWUIlgs3Ar_3FRmC-4n-KS_Uc5eZE',
    appId: '1:22778761281:ios:625a6dcc38d655a54a36c0',
    messagingSenderId: '22778761281',
    projectId: 'my-project-8e1a9',
    storageBucket: 'my-project-8e1a9.appspot.com',
    iosBundleId: 'com.example.secondone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqKZIWUIlgs3Ar_3FRmC-4n-KS_Uc5eZE',
    appId: '1:22778761281:ios:2117d8a5b590c8b34a36c0',
    messagingSenderId: '22778761281',
    projectId: 'my-project-8e1a9',
    storageBucket: 'my-project-8e1a9.appspot.com',
    iosBundleId: 'com.example.secondone.RunnerTests',
  );
}
